name: Maderwerks
favicon: null
layout_spectrum: 0.7477741865441203
typography_spectrum: 0.6026890892535448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.46107404958456755
  lightness: 0.06986778764985502
  saturation: 0.6077466213610023
  rhythmicContrast: 0.6130537511780858
purpose: []
